name: Build React App

on:
  workflow_dispatch:
  push:
    branches: ['main']
env:
    CI: false
    PUBLIC_URL: /simple-stats/build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js 14.20.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.1
          
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.6.0

      - name: Build web bundle
        run: npm run build

      - name: Update list.csv
        run: |
          wget https://kevinaird.github.io/simple-stats/build/reports/list.csv
          mv list.csv build/reports
  
      - name: Pushes bundle 
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build'
          destination_repo: 'kevinaird/kevinaird.github.io'
          destination_folder: 'simple-stats'
          user_email: 'kevinaird@gmail.com'
          user_name: 'kevinaird'
          commit_message: 'Pushing built simple-stats react app'
